name: .net 6

on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build 
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish --no-restore --no-build --output ./publish

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: ./publish


    
